### ISSUE TITLE
Target //oak/server:oak_manager can't be built on its own

### ISSUE THREAD

**Issue by aalmos** [project-oak/oak#47]
If you build only oak_manager with `bazel build --config=enc-sim //oak/server:oak_manager` you'll meet the following error:

 ```
C++ compilation of rule '@linux_sgx//:urts_sim' failed (Exit 1) x86_64-elf-g++ failed: error executing command external/com_google_asylo_toolchain/toolchain/bin/x86_64-elf-g++ -isystemasylo/platform/posix/include -isystemasylo/platform/system/include ... (remaining 86 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/linux_sgx/common/inc/internal/se_wrapper.h:40:0,
                 from external/linux_sgx/psw/urts/linux/urts_internal.cpp:40:
external/linux_sgx/common/inc/internal/se_thread.h:43:10: fatal error: sys/syscall.h: No such file or directory
 #include <sys/syscall.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Target //oak/server:oak_manager failed to build
```

When it'll come to writing tests IMO it'll be problematic.

**Comment by anghelcovici** [comment]
The oak_manager is part of the untrusted code so it needs to be build with the normal toolchain (hence without the --config=enc-sim option). I will add this in the build instructions. I've checked and it builds without it.
