### ISSUE TITLE
Build failure for fuzzing target

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#349]
Not sure why it started failing, see https://oss-fuzz-build-logs.storage.googleapis.com/index.html#oak

@ipetr0v could you take a look? it may related to the other bazel changes

```
Starting Step #4
Step #4: Already have image: gcr.io/oss-fuzz/oak
Step #4: ---------------------------------------------------------------
Step #4: ar: creating /usr/lib/libFuzzingEngine.a
Step #4: Compiling libFuzzer to /usr/lib/libFuzzingEngine.a...  done.
Step #4: CC=clang
Step #4: CXX=clang++
Step #4: CFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link
Step #4: CXXFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++
Step #4: ---------------------------------------------------------------
Step #4: ++ for f in '${CFLAGS}'
Step #4: ++ echo --conlyopt=-O1 --linkopt=-O1
Step #4: ++ for f in '${CFLAGS}'
Step #4: ++ echo --conlyopt=-fno-omit-frame-pointer --linkopt=-fno-omit-frame-pointer
Step #4: ++ for f in '${CFLAGS}'
Step #4: ++ echo --conlyopt=-gline-tables-only --linkopt=-gline-tables-only
Step #4: ++ for f in '${CFLAGS}'
Step #4: ++ echo --conlyopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --linkopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
Step #4: ++ for f in '${CFLAGS}'
Step #4: ++ echo --conlyopt=-fsanitize=address --linkopt=-fsanitize=address
Step #4: ++ for f in '${CFLAGS}'
Step #4: ++ echo --conlyopt=-fsanitize-address-use-after-scope --linkopt=-fsanitize-address-use-after-scope
Step #4: ++ for f in '${CFLAGS}'
Step #4: ++ echo --conlyopt=-fsanitize=fuzzer-no-link --linkopt=-fsanitize=fuzzer-no-link
Step #4: ++ for f in '${CXXFLAGS}'
Step #4: ++ echo --cxxopt=-O1 --linkopt=-O1
Step #4: ++ for f in '${CXXFLAGS}'
Step #4: ++ echo --cxxopt=-fno-omit-frame-pointer --linkopt=-fno-omit-frame-pointer
Step #4: ++ for f in '${CXXFLAGS}'
Step #4: ++ echo --cxxopt=-gline-tables-only --linkopt=-gline-tables-only
Step #4: ++ for f in '${CXXFLAGS}'
Step #4: ++ echo --cxxopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --linkopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
Step #4: ++ for f in '${CXXFLAGS}'
Step #4: ++ echo --cxxopt=-fsanitize=address --linkopt=-fsanitize=address
Step #4: ++ for f in '${CXXFLAGS}'
Step #4: ++ echo --cxxopt=-fsanitize-address-use-after-scope --linkopt=-fsanitize-address-use-after-scope
Step #4: ++ for f in '${CXXFLAGS}'
Step #4: ++ echo --cxxopt=-fsanitize=fuzzer-no-link --linkopt=-fsanitize=fuzzer-no-link
Step #4: ++ for f in '${CXXFLAGS}'
Step #4: ++ echo --cxxopt=-stdlib=libc++ --linkopt=-stdlib=libc++
Step #4: ++ '[' address = undefined ']'
Step #4: + readonly 'EXTRA_BAZEL_FLAGS=--conlyopt=-O1 --linkopt=-O1
Step #4: --conlyopt=-fno-omit-frame-pointer --linkopt=-fno-omit-frame-pointer
Step #4: --conlyopt=-gline-tables-only --linkopt=-gline-tables-only
Step #4: --conlyopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --linkopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
Step #4: --conlyopt=-fsanitize=address --linkopt=-fsanitize=address
Step #4: --conlyopt=-fsanitize-address-use-after-scope --linkopt=-fsanitize-address-use-after-scope
Step #4: --conlyopt=-fsanitize=fuzzer-no-link --linkopt=-fsanitize=fuzzer-no-link
Step #4: --cxxopt=-O1 --linkopt=-O1
Step #4: --cxxopt=-fno-omit-frame-pointer --linkopt=-fno-omit-frame-pointer
Step #4: --cxxopt=-gline-tables-only --linkopt=-gline-tables-only
Step #4: --cxxopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --linkopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
Step #4: --cxxopt=-fsanitize=address --linkopt=-fsanitize=address
Step #4: --cxxopt=-fsanitize-address-use-after-scope --linkopt=-fsanitize-address-use-after-scope
Step #4: --cxxopt=-fsanitize=fuzzer-no-link --linkopt=-fsanitize=fuzzer-no-link
Step #4: --cxxopt=-stdlib=libc++ --linkopt=-stdlib=libc++'
Step #4: + EXTRA_BAZEL_FLAGS='--conlyopt=-O1 --linkopt=-O1
Step #4: --conlyopt=-fno-omit-frame-pointer --linkopt=-fno-omit-frame-pointer
Step #4: --conlyopt=-gline-tables-only --linkopt=-gline-tables-only
Step #4: --conlyopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --linkopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
Step #4: --conlyopt=-fsanitize=address --linkopt=-fsanitize=address
Step #4: --conlyopt=-fsanitize-address-use-after-scope --linkopt=-fsanitize-address-use-after-scope
Step #4: --conlyopt=-fsanitize=fuzzer-no-link --linkopt=-fsanitize=fuzzer-no-link
Step #4: --cxxopt=-O1 --linkopt=-O1
Step #4: --cxxopt=-fno-omit-frame-pointer --linkopt=-fno-omit-frame-pointer
Step #4: --cxxopt=-gline-tables-only --linkopt=-gline-tables-only
Step #4: --cxxopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --linkopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
Step #4: --cxxopt=-fsanitize=address --linkopt=-fsanitize=address
Step #4: --cxxopt=-fsanitize-address-use-after-scope --linkopt=-fsanitize-address-use-after-scope
Step #4: --cxxopt=-fsanitize=fuzzer-no-link --linkopt=-fsanitize=fuzzer-no-link
Step #4: --cxxopt=-stdlib=libc++ --linkopt=-stdlib=libc++'
Step #4: + readonly 'NO_VPTR=--copt=-fno-sanitize=vptr --linkopt=-fno-sanitize=vptr'
Step #4: + NO_VPTR='--copt=-fno-sanitize=vptr --linkopt=-fno-sanitize=vptr'
Step #4: + FUZZER_TARGETS=('oak/server:wasm_node_fuzz')
Step #4: + readonly FUZZER_TARGETS
Step #4: + bazel build --client_env=CC=clang --client_env=CXX=clang++ --dynamic_mode=off --spawn_strategy=standalone --genrule_strategy=standalone --copt=-fno-sanitize=vptr --linkopt=-fno-sanitize=vptr --strip=never --linkopt=-lc++ --linkopt=-pthread --cxxopt=-std=c++11 --copt=-fsanitize=fuzzer --linkopt=-fsanitize=fuzzer --remote_cache=https://storage.googleapis.com/oak-bazel-cache --remote_upload_local_results=false --conlyopt=-O1 --linkopt=-O1 --conlyopt=-fno-omit-frame-pointer --linkopt=-fno-omit-frame-pointer --conlyopt=-gline-tables-only --linkopt=-gline-tables-only --conlyopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --linkopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --conlyopt=-fsanitize=address --linkopt=-fsanitize=address --conlyopt=-fsanitize-address-use-after-scope --linkopt=-fsanitize-address-use-after-scope --conlyopt=-fsanitize=fuzzer-no-link --linkopt=-fsanitize=fuzzer-no-link --cxxopt=-O1 --linkopt=-O1 --cxxopt=-fno-omit-frame-pointer --linkopt=-fno-omit-frame-pointer --cxxopt=-gline-tables-only --linkopt=-gline-tables-only --cxxopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --linkopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --cxxopt=-fsanitize=address --linkopt=-fsanitize=address --cxxopt=-fsanitize-address-use-after-scope --linkopt=-fsanitize-address-use-after-scope --cxxopt=-fsanitize=fuzzer-no-link --linkopt=-fsanitize=fuzzer-no-link --cxxopt=-stdlib=libc++ --linkopt=-stdlib=libc++ oak/server:wasm_node_fuzz
Step #4: Extracting Bazel installation...
Step #4: Starting local Bazel server and connecting to it...
Step #4: INFO: Invocation ID: e978841f-40ea-44f1-9fba-5926da666420
Step #4: Loading: 
Step #4: Loading: 0 packages loaded
Step #4: Loading: 0 packages loaded
Step #4: Loading: 0 packages loaded
Step #4: Loading: 0 packages loaded
Step #4: Loading: 0 packages loaded
Step #4: Loading: 0 packages loaded
Step #4: Analyzing: target //oak/server:wasm_node_fuzz (1 packages loaded)
Step #4: Analyzing: target //oak/server:wasm_node_fuzz (1 packages loaded, 0 targets configured)
Step #4: Analyzing: target //oak/server:wasm_node_fuzz (18 packages loaded, 40 targets configured)
Step #4: Analyzing: target //oak/server:wasm_node_fuzz (24 packages loaded, 50 targets configured)
Step #4: Analyzing: target //oak/server:wasm_node_fuzz (24 packages loaded, 50 targets configured)
Step #4: INFO: Analyzed target //oak/server:wasm_node_fuzz (39 packages loaded, 900 targets configured).
Step #4: INFO: Found 1 target...
Step #4: [0 / 18] [Prepa] BazelWorkspaceStatusAction stable-status.txt ... (2 actions, 0 running)
Step #4: ERROR: /builder/home/.cache/bazel/_bazel_root/872aac72dffae06b4e2a5b0308508d03/external/com_google_absl/absl/base/BUILD.bazel:171:1: undeclared inclusion(s) in rule '@com_google_absl//absl/base:base':
Step #4: this rule is missing dependency declarations for the following files included by 'external/com_google_absl/absl/base/internal/unscaledcycleclock.cc':
Step #4:   '/usr/local/lib/clang/10.0.0/share/asan_blacklist.txt'
Step #4: Target //oak/server:wasm_node_fuzz failed to build
Step #4: Use --verbose_failures to see the command lines of failed build steps.
Step #4: INFO: Elapsed time: 17.612s, Critical Path: 1.11s
Step #4: INFO: 4 processes: 4 local.
Step #4: FAILED: Build did NOT complete successfully
Step #4: FAILED: Build did NOT complete successfully
Finished Step #4
ERROR
ERROR: build step 4 "gcr.io/oss-fuzz/oak" failed: exit status 1
```

**Comment by tiziano88** [comment]
Also a different but possibly related failure happens on Travis when validating the fuzzing config: https://travis-ci.org/google/oss-fuzz/jobs/621069420

**Comment by tiziano88** [comment]
See https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-build-failures

**Comment by ipetr0v** [comment]
Looks like their docker image lacks Asylo toolchain, that is provided by official Asylo docker image, since while running `bazel sync` I get the following error:
```
INFO: Call stack for the definition of repository 'com_google_asylo_toolchain' which is a _instantiate_crosstool (rule definition at /root/.cache/bazel/_bazel_root/872aac72dffae06b4e2a5b0308508d03/external/com_google_asylo/asylo/bazel/asylo_deps.bzl:126:26):
 - /root/.cache/bazel/_bazel_root/872aac72dffae06b4e2a5b0308508d03/external/com_google_asylo/asylo/bazel/asylo_deps.bzl:144:5
 - /src/oak/WORKSPACE:144:1
ERROR: An error occurred during the fetch of repository 'com_google_asylo_toolchain':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/872aac72dffae06b4e2a5b0308508d03/external/com_google_asylo/asylo/bazel/asylo_deps.bzl", line 116
                installation_path(<5 more arguments>)
        File "/root/.cache/bazel/_bazel_root/872aac72dffae06b4e2a5b0308508d03/external/com_google_asylo/asylo/bazel/installation_path.bzl", line 66, in installation_path
                _fail_if_directory_does_not_exist(<3 more arguments>)
        File "/root/.cache/bazel/_bazel_root/872aac72dffae06b4e2a5b0308508d03/external/com_google_asylo/asylo/bazel/installation_path.bzl", line 23, in _fail_if_directory_does_not_exist
                fail(<1 more arguments>)
Install path to Asylo toolchain [default] does not exist: /opt/asylo/toolchains/default
INFO: SHA256 (https://static.rust-lang.org/dist/2019-11-06/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz) = bccc445c43bb3e0ac24e7a419c4fe0292d53c02b26a96d0962fe85d74f95d826
INFO: SHA256 (https://static.rust-lang.org/dist/2019-11-06/rust-std-nightly-x86_64-unknown-linux-gnu.tar.gz) = 4f3ec5d84009d97d406298cf734c87114af2a2cb164ee3340e1606dcdfe071cc
ERROR: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/872aac72dffae06b4e2a5b0308508d03/external/com_google_asylo/asylo/bazel/asylo_deps.bzl", line 116
                installation_path(<5 more arguments>)
        File "/root/.cache/bazel/_bazel_root/872aac72dffae06b4e2a5b0308508d03/external/com_google_asylo/asylo/bazel/installation_path.bzl", line 66, in installation_path
                _fail_if_directory_does_not_exist(<3 more arguments>)
        File "/root/.cache/bazel/_bazel_root/872aac72dffae06b4e2a5b0308508d03/external/com_google_asylo/asylo/bazel/installation_path.bzl", line 23, in _fail_if_directory_does_not_exist
                fail(<1 more arguments>)
Install path to Asylo toolchain [default] does not exist: /opt/asylo/toolchains/default
```

**Comment by tiziano88** [comment]
Note that the current only fuzz target does not actually require Asylo to be built. See https://github.com/google/oss-fuzz/blob/master/projects/oak/build.sh . But perhaps `bazel sync` will check for the Asylo toolchain to be installed when syncing the Asylo Bazel dependency; if so we should avoid `bazel sync` entirely, and assume that bazel will lazily sync only the dependencies that are actually used as part of the build.

**Comment by ipetr0v** [comment]
I'm trying to delete different build flags to see if `wasm_node_fuzz` is compiling.
While doing this I have got the following error:
```
ERROR: /src/oak/oak/server/BUILD:71:1: C++ compilation of rule '//oak/server:wasm_node_fuzz' failed (Exit 1)
oak/server/wasm_node_fuzzer.cc:8:77: error: too few arguments to function call, expected 3, have 2
  std::unique_ptr<oak::WasmNode> node = oak::WasmNode::Create("test", module);
                                        ~~~~~~~~~~~~~~~~~~~~~               ^
./oak/server/wasm_node.h:32:3: note: 'Create' declared here
  static std::unique_ptr<WasmNode> Create(BaseRuntime* runtime, const std::string& name,
  ^
1 error generated.
Target //oak/server:wasm_node_fuzz failed to build
```
Looks like fuzzer is trying to create a node with 2 parameters:
https://github.com/project-oak/oak/blob/e89cfb927a434e544c378c6c7669c87ccbc6c636/oak/server/wasm_node_fuzzer.cc#L6-L10

But there are actually 3:
https://github.com/project-oak/oak/blob/e89cfb927a434e544c378c6c7669c87ccbc6c636/oak/server/wasm_node.h#L29-L33

**Comment by tiziano88** [comment]
That seems to be caused by #341 cc @daviddrysdale .

**Comment by ipetr0v** [comment]
So basically address sanitizer implicitly adds a dependency on `/usr/local/lib/clang/10.0.0/share/asan_blacklist.txt` in every compiled file (even external ones). And Bazel could not compile targets because all dependencies should be explicitly included in `BUILD` files.


I tried to create a local blacklist file, reference it as `data` in the BUILD file:
```
cc_library(
    name = "wasm_node",
    srcs = [
        "wabt_output.cc",
        "wasm_node.cc",
    ],
    hdrs = [
        "wabt_output.h",
        "wasm_node.h",
    ],
    deps = [
        ...
    ],
    data = ["//oak/server:blacklist.txt"],
)
```
and also used:
```
--cxxopt="-fsanitize-blacklist=oak/server/blacklist.txt" --conlyopt="-fsanitize-blacklist=oak/server/blacklist.txt"
```
with a local `blacklist.txt` file.
But this command does not rewrite the default blacklist, it just adds a new one. And also this doesn't solve the fact, that all other project and external files also depend on `asan_blacklist.txt`.

**Comment by ipetr0v** [comment]
I have found a flag, that causes this behavior:
```bash
$ bazel build --cxxopt=-fsanitize=address //oak/server:wasm_node
INFO: Analyzed target //oak/server:wasm_node (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/872aac72dffae06b4e2a5b0308508d03/external/com_google_absl/absl/numeric/BUILD.bazel:27:1: undeclared inclusion(s) in rule '@com_google_absl//absl/numeric:int128':
this rule is missing dependency declarations for the following files included by 'external/com_google_absl/absl/numeric/int128.cc':
  '/usr/local/lib/clang/10.0.0/share/asan_blacklist.txt'
Target //oak/server:wasm_node failed to build
```

**Comment by ipetr0v** [comment]
All of this takes place in the following docker container:
https://github.com/google/oss-fuzz/blob/6cb657fe6a92ce05df5595da90e17c99ea17a041/projects/oak/Dockerfile

**Comment by tiziano88** [comment]
Could you try with `--strategy=local`? https://docs.bazel.build/versions/master/command-line-reference.html#flag--strategy

**Comment by daviddrysdale** [comment]
The #341 -related failure is because the fuzzer driver wasn't updated in that PR, which wasn't visible because nothing in our CI builds exercises that target (which in turn is basically #346).

Hopefully #351 should fix the build problem, but making this kind of thing visible via automation (#346) is still open.

**Comment by ipetr0v** [comment]
`--strategy=local` also doesn't help.
And it seems that [gRPC](https://github.com/grpc) also has the same problem:
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#grpc
```
Step #4: ERROR: /src/grpc/BUILD:468:1: undeclared inclusion(s) in rule '//:gpr_base':
Step #4: this rule is missing dependency declarations for the following files included by 'src/core/lib/gpr/env_windows.cc':
Step #4:   '/usr/local/lib/clang/10.0.0/share/asan_blacklist.txt'
```
Submitted an issue https://github.com/google/oss-fuzz/issues/3093

**Comment by ipetr0v** [comment]
Looks like this issue was resolved in https://github.com/google/oss-fuzz/pull/3148

The last Oak build is successful (12/18/2019, 1:36:22 AM):
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#oak
